import React from 'react';
import type { Metadata } from 'next';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import HeaderNav from '@/components/headerNav';
import AntDesignProvider from '@/providers/AntDesignProvider';

export const metadata: Metadata = {
  title: 'Baemin',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='w-full h-fit'>
        <AntdRegistry>
          <AntDesignProvider>
            <HeaderNav />
            {children}
          </AntDesignProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
